### ISSUE TITLE
can not install it on mac os

### ISSUE THREAD

**Issue by XuandongZhao** [slimgroup/PyCurvelab#4]
I have already done the first two steps:
Clone this repsitory.
Set these required environment variables:
FDCT: folder where your CurveLab installation is
FFTW: folder where your fftw installation is

but when I run `python setup.py build` , it has an error with gcc.

PyCurvelab git:(master) ✗ python setup.py build
running build
running build_py
copying src/fdct2_wrapper.py -> build/lib.macosx-10.7-x86_64-3.6/pyct
running build_ext
building '_fdct2_wrapper' extension
swigging src/fdct2_wrapper.i to src/fdct2_wrapper_wrap.cpp
swig -python -c++ -o src/fdct2_wrapper_wrap.cpp src/fdct2_wrapper.i
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/zhaoxuandong/opt/anaconda2/envs/python3/include -arch x86_64 -I/Users/zhaoxuandong/opt/anaconda2/envs/python3/include -arch x86_64 -I/Users/zhaoxuandong/opt/CurveLab-2.1.3/fdct_wrapping_cpp/src -I/Users/zhaoxuandong/opt/fftw-3.3.8/include -I/Users/zhaoxuandong/opt/anaconda2/envs/python3/lib/python3.6/site-packages/numpy/core/include/numpy -Isrc -I/Users/zhaoxuandong/opt/anaconda2/envs/python3/include/python3.6m -c src/fdct2_wrapper.cpp -o build/temp.macosx-10.7-x86_64-3.6/src/fdct2_wrapper.o
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on
      the command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]
In file included from src/fdct2_wrapper.cpp:1:
In file included from src/fdct2_wrapper.hpp:1:
In file included from src/fdct_wrapper.hpp:17:
In file included from /Users/zhaoxuandong/opt/anaconda2/envs/python3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/zhaoxuandong/opt/anaconda2/envs/python3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /Users/zhaoxuandong/opt/anaconda2/envs/python3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:
/Users/zhaoxuandong/opt/anaconda2/envs/python3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: 
      "Using deprecated NumPy API, disable it with "          "#define
      NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
In file included from src/fdct2_wrapper.cpp:1:
In file included from src/fdct2_wrapper.hpp:3:
In file included from /Users/zhaoxuandong/opt/CurveLab-2.1.3/fdct_wrapping_cpp/src/fdct_wrapping.hpp:10:
/Users/zhaoxuandong/opt/CurveLab-2.1.3/fdct_wrapping_cpp/src/fdct_wrapping_inc.hpp:10:10: fatal error: 
      'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
2 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1

My gcc path is `/usr/bin/gcc` gcc version is that 
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

How can I fix it? Do you have any suggestions?

**Comment by henryk-modzelewski** [comment]
Which version of Mac OS X are you using? And what compilers? It looks like it is not able to find iostream which is typically part of compiler package.

**Comment by XuandongZhao** [comment]
I use Mac OS 10.15.1(Catalina). Actually I don't know in which part the setup.py called the compiler. I found in Command Line that it used GCC and my GCC version is Apple clang version 11.0.0 (clang-1100.0.33.8) Target: x86_64-apple-darwin19.0.0.

**Comment by XuandongZhao** [comment]
I finally solved it!

Change setup to this:

setup(name='pyct',
      version='1.0',
      description='Python Wrappers for CurveLab-2.0',
      author='Darren Thomson and Gilles Hennenfent',
      author_email='dthomson,ghennenfent@eos.ubc.ca',
      url='http://slim.eos.ubc.ca',
      ext_package='pyct',
      ext_modules=[Extension('_fdct2_wrapper',
                   [os.path.join('src', 'fdct2_wrapper.cpp'), os.path.join('src', 'fdct2_wrapper.i')],
                   include_dirs=[fdct2, fftw_inc, npy_inc, pycl_inc],
                   library_dirs=[fdct2, fftw_lib], libraries=['fdct_wrapping', 'fftw'],swig_opts=['-c++'],
                   extra_compile_args = ['-stdlib=libc++'],
                   extra_link_args=['-stdlib=libc++']),
                   Extension('_fdct3_wrapper',
                   [os.path.join('src', 'fdct3_wrapper.cpp'), os.path.join('src', 'fdct3_wrapper.i')],
                   include_dirs=[fdct3, fftw_inc, npy_inc, pycl_inc],
                   library_dirs=[fdct3, fftw_lib], libraries=['fdct3d', 'fftw'],swig_opts=['-c++'],
                   extra_compile_args = ['-stdlib=libc++'],
                   extra_link_args=['-stdlib=libc++'])],
      package_dir={'pyct': 'src'}, 
      packages=['pyct']
      )

**Comment by henryk-modzelewski** [comment]
Well. I cannot reproduce your problem on pre-Catalina systems, and I do not have yet Catalina around. It is too buggy to install. I suspect it might have something to do with problems related to Catalina's Xcode. I will close it, but thanks for debugging it. Maybe somebody else will run into the same problem.
