### ISSUE TITLE
Installation problem in Google Colab

### ISSUE THREAD

**Issue by adhaka3** [slimgroup/PyCurvelab#5]
Hi
I am trying to use the curvelet filter in python. I was wondering if there is any way to use this repository in Google colab. I cloned the repository but got confused about how to enter the FFTW and FTCD variable.

**Comment by henryk-modzelewski** [comment]
I do not use Google Colab, so I am not sure what would the the specific installation procedure. Basically you the compilation rely on existing compiled FFTW/FDCT and environment variables point to home of those installations  (as per installation notes). So you have to have them installed first. end then fine those environments. If you do not work in SHELL environment, you will have to define those variable in all makefiles, wherever those are mentioned.
