### ISSUE TITLE
AttributeError: 'module' object has no attribute 'fdct2'`

### ISSUE THREAD

**Issue by AtilaSaraiva** [slimgroup/PyCurvelab#6]
Hello guys!

I am having trouble installing PyCurvelab, since in spite of having installed both FFTW and Curvelab successfully, when I run python setup.py build install inside PyCurvelab folder and try to use the module it says that pyct doesn't have the fdct2 procedure. 
What I get whenever I run python setup.py build is:
https://pastebin.com/yisPEY9t

Depite the lack of errors, I am still not able to run pyct as follows:

>>> import pyct
>>> pyct.fdct2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'fdct2'

I feel that there is a high likelyhood of this issue being a silly problem. Nevertheless, I would very much appreciate any help you can give me.

Best reggards.

**Comment by AtilaSaraiva** [comment]
I managed to solve the problem guys. I was seemingly using the wrong branch since I use python 2.
Sorry for the trouble.

**Comment by henryk-modzelewski** [comment]
No problem. I am glad you got it. :)
