### ISSUE TITLE
AttributeError: module 'pyct' has no attribute 'fdct2'

### ISSUE THREAD

**Issue by mrin9san** [slimgroup/PyCurvelab#8]
I am a newbie to Ubuntu. I installed SWIG, FFTW and CurveLab. I am using Python 3.6.
This is the folder where I have put FFTW - `/home/user1/fftw-2.1.5/`
This is the folder where I have put CurveLab - `/home/user1/CurveLab/CurveLab-2.1.3/`

However got stumbled in second step- 
"Set these required environment variables:
    FDCT: folder where your CurveLab installation is
    FFTW: folder where your fftw installation is" 

I typed in command
 ` sudo -H gedit /etc/environment` and put following lines in the environment list.
```
FDCT="/home/user1/CurveLab/CurveLab-2.1.3/"
FFTW="/home/user1/fftw-2.1.5/"
```
Now, continued with rest of installation. The module pyct does get imported. However when I try to use function fdct2 it shows  `AttributeError: module 'pyct' has no attribute 'fdct2'`

I know I have made some silly issue with paths and all. Just not getting where the exact issue might be. Any help will be appreciated.

**Comment by kkothari93** [comment]
I faced a similar issue with Python3. I fixed the source files manually. First you would need to find where the library is installed. For that, just run the following in a Python3 shell instance:
```
import pyct as ct
print(ct.__file__) # gives the path where the __init__.py file is located
```
Essentially if you look at the `__init__.py` file within `src` folder you will notice that it does not import all the required files (this is if you are using the master branch, i.e. Python3 branch). So you should add:
```
from .fdct import *

from .fdct2 import *

from .fdct3 import *

from .test import test, normtest
``` 

This should fix the imports. You might get another error after this: if so, you can post it here. I can help as I went through the exact same thing.

**Comment by SLim2592** [comment]
I'm under mac OS catalina, I installed everything as it should be, but when executing the code I get the following errors : 
the script : 

`from pyct import fdct2`

`n = (50,50)` 
`nbs = 4` 
`nba = 8`

`l= fdct2(n, nbs, nba, True,norm = True)`

the errors : 
`AttributeError: type object 'fdct' has no attribute 'fdct' `

I even tried to import the module differently like this : 
`from pyct.fdct2 import fdct2`

but I have the same errors : 
`AttributeError: type object 'fdct' has no attribute 'fdct'`

if anyone could help me ??

**Comment by jtherrmann** [comment]
@SLim2592 My PR should fix that error. You can install from my fork for now, if you want.

**Comment by abh886** [comment]
Hi.. I have one issue.. When I try to build the install, I am getting this error, can someone please explain why this is happening?

(base) PS C:\Users\AbhinavN\PyCurvelab-master> python setup.py build install
running build
running build_py
creating build\lib.win-amd64-3.8
creating build\lib.win-amd64-3.8\pyct
copying pyct\CLarray.py -> build\lib.win-amd64-3.8\pyct
copying pyct\fdct.py -> build\lib.win-amd64-3.8\pyct
copying pyct\fdct2.py -> build\lib.win-amd64-3.8\pyct
copying pyct\fdct2_wrapper.py -> build\lib.win-amd64-3.8\pyct
copying pyct\fdct3.py -> build\lib.win-amd64-3.8\pyct
copying pyct\test.py -> build\lib.win-amd64-3.8\pyct
copying pyct\__init__.py -> build\lib.win-amd64-3.8\pyct
running build_ext
building '_fdct2_wrapper' extension
swigging pyct\fdct2_wrapper.i to pyct\fdct2_wrapper_wrap.cpp
C:\swigwin-4.0.2\swig.exe -python -c++ -o pyct\fdct2_wrapper_wrap.cpp pyct\fdct2_wrapper.i
creating build\temp.win-amd64-3.8
creating build\temp.win-amd64-3.8\Release
creating build\temp.win-amd64-3.8\Release\pyct
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:/Users/Abhinav/OneDrive - Ennoventure Inc/PyCurvelab-master/CurveLab-2.1.3/fdct_wrapping_cpp\src" "-IC:/Users/Abhinav/OneDrive - Ennoventure Inc/PyCurvelab-master/fftw-2.1.5/include" -IC:\Users\AbhinavN\anaconda3\lib\site-packages\numpy\core\include\numpy -Ipyct -IC:\Users\AbhinavN\anaconda3\include -IC:\Users\AbhinavN\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tppyct\fdct2_wrapper.cpp /Fobuild\temp.win-amd64-3.8\Release\pyct\fdct2_wrapper.obj
fdct2_wrapper.cpp
C:\Users\AbhinavN\anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
pyct\fdct2_wrapper.hpp(3): fatal error C1083: Cannot open include file: 'fdct_wrapping.hpp': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by abh886** [comment]
Hi. When I run setup.py, I get this message
C:\Users\AbhinavN\anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
pyct\fdct2_wrapper.hpp(3): fatal error C1083: Cannot open include file: 'fdct_wrapping.hpp': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Can somebody please explain why this is happening?**
